coverage:
  range: 50..90
  round: down
  precision: 2
  status:
    project:
      # full project
      default:
        target: 70%
        threshold: 5%
        base: auto
    patch:
      # just the lines changed
      default:
        target: 50%
        threshold: 10%
        base: auto
        only_pulls: false
