# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# To install:
# pip install pre-commit
# pre-commit install --allow-missing-config
repos:
- repo: https://github.com/akaihola/darker
  rev: 1.7.2
  hooks:
    - id: darker
      args:
        - --lint
        - ruff check
      additional_dependencies:
          - ruff==0.3.7